/**
  *******************************************************************
  * @file               : drivers_alloc.c
  * @date               : 
  * @author             : Auto-generated by gen_drivers_alloc
  *******************************************************************
  * @brief
  *******************************************************************
  */


/********************/
/* Private includes */
/********************/
#include "../Inc/drivers_alloc.h"
#include "usart.h"
#include "gpio.h"
#include "stm32f769i_discovery_lcd.h"

/*******************/
/* Private typedef */
/*******************/

/*******************/
/* Private defines */
/*******************/

/*********************/
/* Private constants */
/*********************/
const GPIO_ALLOC GPIO_PJ5 = {
    .gpio = GPIOJ,
    .pin = GPIO_PIN_5,
};
const GPIO_ALLOC GPIO_PJ13 = {
    .gpio = GPIOJ,
    .pin = GPIO_PIN_13,
};
const DRIVER_ALLOC DRIVERS_ALLOC[] = {
    { (uint8_t*)"SERIAL_MAIN", USART, INOUT, (void*) &huart1, 0 },
    { (uint8_t*)"ACT_LED", GPIO, OUT, (void*) &GPIO_PJ5, 1 },
    { (uint8_t*)"ERR_LED", GPIO, OUT, (void*) &GPIO_PJ13, 2 },
    { (uint8_t*)"LCD", LCD, INOUT, (void*) 0, 3 },
};
uint8_t USART1_BUFFER[USART_BUFFER_SIZE];

/******************/
/* Private macros */
/******************/

/*********************/
/* Private variables */
/*********************/

/*********************/
/* Private functions */
/*********************/

/********************/
/* Public functions */
/********************/
void drivers_init()
{
    // USART1 initialization
    MX_USART1_UART_Init();

    // USART1 initialization
    HAL_UART_Receive_IT(&huart1, USART1_BUFFER, 1);

    // GPIO initialization
    MX_GPIO_Init();

    // LCD initialization
    BSP_LCD_Init();
    BSP_LCD_LayerDefaultInit(0, LCD_FB_START_ADDRESS);
    BSP_LCD_DisplayOff();

}

void USART1_it_handler()
{
    HAL_UART_IRQHandler(&huart1);
}
