/**
  *******************************************************************
  * @file               : drivers_alloc.c
  * @date               : Generated on 26-09-2025
  * @author             : Auto-generated by gen_drivers_alloc
  *******************************************************************
  * @brief
  *******************************************************************
  */


/********************/
/* Private includes */
/********************/
#include "../Inc/drivers_alloc.h"
#include "usart.h"

/*******************/
/* Private typedef */
/*******************/

/*******************/
/* Private defines */
/*******************/

/*********************/
/* Private constants */
/*********************/
const GPIO_ALLOC GPIO_PJ5 = {
    .gpio = GPIOJ,
    .pin = GPIO_PIN_5,
};
const GPIO_ALLOC GPIO_PJ13 = {
    .gpio = GPIOJ,
    .pin = GPIO_PIN_13,
};
const DRIVER_ALLOC DRIVERS_ALLOC[] = {
    { (uint8_t*)"SERIAL_MAIN", USART, INOUT, (void*) &huart1, 0 },
    { (uint8_t*)"ACT_LED", GPIO, OUT, (void*) &GPIO_PJ5, 1 },
    { (uint8_t*)"ERR_LED", GPIO, OUT, (void*) &GPIO_PJ13, 2 },
};

/******************/
/* Private macros */
/******************/

/*********************/
/* Private variables */
/*********************/

/*********************/
/* Private functions */
/*********************/

/********************/
/* Public functions */
/********************/
