/**
  *******************************************************************
  * @file               : drivers_alloc.h
  * @date               : 
  * @author             : Auto-generated by gen_drivers_alloc
  *******************************************************************
  * @brief
  *******************************************************************
  */

#ifndef DRIVERS_ALLOC_H
#define DRIVERS_ALLOC_H

/************/
/* Includes */
/************/
#include "drivers_types.h"

/********************/
/* Exported defines */
/********************/
#define DRIVERS_ALLOC_SIZE 4
#define DRIVER_ACTIVATE_USART
#define DRIVER_ACTIVATE_GPIO
#define DRIVER_ACTIVATE_LCD
#define USART_BUFFER_SIZE 32

/******************/
/* Exported types */
/******************/
typedef struct
{
    uint8_t buffer[USART_BUFFER_SIZE];
    uint8_t size;
} USART_RX_BUFFER;

/**********************/
/* Exported constants */
/**********************/
extern const DRIVER_ALLOC DRIVERS_ALLOC[];
extern USART_RX_BUFFER USART1_BUFFER;

/**********************/
/* Exported variables */
/**********************/

/******************/
/* Exported macro */
/******************/

/**********************/
/* Exported functions */
/**********************/
void drivers_init();

#endif
