/**
  *******************************************************************
  * @file               : drivers_alloc.h
  * @date               : 
  * @author             : Auto-generated by gen_drivers_alloc
  *******************************************************************
  * @brief
  *******************************************************************
  */

#ifndef DRIVERS_ALLOC_H
#define DRIVERS_ALLOC_H

/************/
/* Includes */
/************/
#include "drivers_types.h"

/********************/
/* Exported defines */
/********************/
#define DRIVERS_ALLOC_SIZE 4

/******************/
/* Exported types */
/******************/


/**********************/
/* Exported constants */
/**********************/
extern const DRIVER_ALLOC DRIVERS_ALLOC[];

/**********************/
/* Exported variables */
/**********************/

/******************/
/* Exported macro */
/******************/

/**********************/
/* Exported functions */
/**********************/


#endif
